local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Instant Respawn Script by Techy (techwastaken#7592)", "Synapse")
local About = Window:NewTab("About")
local Main = Window:NewTab("Main")
local WelcomeSection = About:NewSection("Thank you for downloading instant respawn script!")
local MainSection = Main:NewSection("Main Section")
local KeybindsSection = Main:NewSection("Keybinds")
WelcomeSection:NewLabel("This script is useful for respawning quick!")
WelcomeSection:NewLabel("Powered by Kavo UI! (Like all my other scripts)")
MainSection:NewButton("Respawn", "Main part of this script, Lets you respawn quickly.", function()
    game.Players.LocalPlayer.Character.Humanoid.Health = 0
	print("Success")
end)
KeybindsSection:NewKeybind("Respawn Keybind", "Keybind for the respawn button.", Enum.KeyCode.K, function()
	print("Success (Keybind)")
	game.Players.LocalPlayer.Character.Humanoid.Health = 0
end)
KeybindsSection:NewKeybind("Toggle UI", "Toggles the UI.", Enum.KeyCode.F, function()
	Library:ToggleUI()
end)
